GET http://localhost:3005/api/productos
Authorization: Bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NjMxYTI0OWI1YmUzMmI1NTZhNGZkNjkiLCJpYXQiOjE3MTQ5MjY5NjMsImV4cCI6MTcxNDk3MDE2M30.S7JTO_JD3iR1K8qUV9zEPQeCnN9hcLEQRcq3npKdObk"
